[hugoVersion]
extended = true
min = "0.84.4"

[[mounts]]
source = 'content'
target = 'content'

[[mounts]]
source = 'data'
target = 'data'

[[mounts]]
source = 'layouts'
target = 'layouts'

[[imports]]
disable = false
ignoreConfig = true
ignoreImports = true
path = "github.com/csswizardry/ct"

[[imports.mounts]]
source = 'ct.css'
target = 'assets/css/libs/ct.css'

[[imports.mounts]]
source = 'ct.css'
target = 'static/css/libs/ct.css'
